name: rossete_v4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  file_picker: ^10.3.7
  flutter:
    sdk: flutter
  get_it: ^9.2.0
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  fonts:
    - family: TDAText
      fonts:
        - asset: fonts/TDAText.ttf
  uses-material-design: true
